{{- if .Values.adminSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.adminSecret.targetSecretName }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: {{ .Values.externalSecret.secretStore.kind }}
  target:
    name: {{ .Values.adminSecret.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_API_KEY
      remoteRef:
        key: {{ .Values.adminSecret.remoteSecretName }}
        property: api_key
{{- end }}
