{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.targetSecretName }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: {{ .Values.externalSecret.secretStore.kind }}
  target:
    name: {{ .Values.externalSecret.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
        property: host
    - secretKey: DB_PORT
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
        property: port
    - secretKey: DB_USERNAME
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
        property: password
    - secretKey: DB_NAME
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
        property: dbname
{{- end }}
