{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecret.secretStore.name }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.env.AWS_REGION | default "us-east-1" }}
{{- end }}
