apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-gateway-admin-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications

  source:
    repoURL: https://github.com/asian-code/CodeGuardian-AI
    targetRevision: main
    path: app/helm-chart/admin-ui
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: llm-gateway

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
