apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codeguardian-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications

  source:
    repoURL: https://github.com/asian-code/CodeGuardian-AI
    targetRevision: main
    path: app/helm-chart/frontend
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: codeguardian

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
