apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-gateway-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications

  source:
    repoURL: https://github.com/c0debyeric/llm-inference-platform
    targetRevision: main
    path: app/helm-chart/backend
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: llm-gateway

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
