replicaCount: 2

image:
  repository: "810749429738.dkr.ecr.us-east-1.amazonaws.com/codeguardian/frontend"
  tag: "latest"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: codeguardian-frontend

service:
  type: LoadBalancer
  port: 8501
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

env:
  BACKEND_URL: "http://codeguardian-backend.codeguardian.svc.cluster.local:8000"
  STREAMLIT_SERVER_PORT: "8501"
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
  STREAMLIT_SERVER_HEADLESS: "true"
  STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

podDisruptionBudget:
  enabled: true
  minAvailable: 1

networkPolicy:
  enabled: true

probes:
  liveness:
    path: /_stcore/health
    initialDelaySeconds: 15
    periodSeconds: 20
    timeoutSeconds: 5
  readiness:
    path: /_stcore/health
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3

nodeSelector: {}
tolerations: []
affinity: {}
